name: Emacs Lisp Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests on Emacs ${{ matrix.emacs-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: ['25.3', '26.3', '27.2', '28.2', '29.4']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Run Tests
        run: emacs --batch --no-init-file --load tests/run-tests.el
